services:
  - type: web
    name: planning-gpt
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install && cd frontend && yarn build
    startCommand: poetry run uvicorn backend.api:app --host=0.0.0.0 --port $PORT
